export const EMPLOYEES = [
    {
      "id": 1,
      "first_name": "Gale",
      "last_name": "Snipe",
      "email": "gsnipe0@hostgator.com",
      "gender": "Female",
      "mobile": "3735925219"
    }, {
      "id": 2,
      "first_name": "Levi",
      "last_name": "McKain",
      "email": "lmckain1@columbia.edu",
      "gender": "Male",
      "mobile": "6531389168"
    }, {
      "id": 3,
      "first_name": "August",
      "last_name": "Gilliland",
      "email": "agilliland2@hexun.com",
      "gender": "Male",
      "mobile": "9374765934"
    }, {
      "id": 4,
      "first_name": "Kristyn",
      "last_name": "Capell",
      "email": "kcapell3@globo.com",
      "gender": "Female",
      "mobile": "2790321639"
    }, {
      "id": 5,
      "first_name": "Bat",
      "last_name": "Warlton",
      "email": "bwarlton4@about.me",
      "gender": "Male",
      "mobile": "6631637597"
    }, {
      "id": 6,
      "first_name": "Briano",
      "last_name": "de la Tremoille",
      "email": "bdelatremoille5@weebly.com",
      "gender": "Male",
      "mobile": "4906820468"
    }, {
      "id": 7,
      "first_name": "Titus",
      "last_name": "Beddard",
      "email": "tbeddard6@issuu.com",
      "gender": "Male",
      "mobile": "8391546942"
    }, {
      "id": 8,
      "first_name": "Cesya",
      "last_name": "Dalligan",
      "email": "cdalligan7@livejournal.com",
      "gender": "Female",
      "mobile": "7964577026"
    }, {
      "id": 9,
      "first_name": "Eada",
      "last_name": "Diplock",
      "email": "ediplock8@go.com",
      "gender": "Female",
      "mobile": "8370840949"
    }, {
      "id": 10,
      "first_name": "Clea",
      "last_name": "Brissard",
      "email": "cbrissard9@senate.gov",
      "gender": "Female",
      "mobile": "2408821274"
    }, {
      "id": 11,
      "first_name": "Charla",
      "last_name": "Nottingam",
      "email": "cnottingama@toplist.cz",
      "gender": "Female",
      "mobile": "5518034504"
    }, {
      "id": 12,
      "first_name": "Clarence",
      "last_name": "Bayle",
      "email": "cbayleb@pen.io",
      "gender": "Male",
      "mobile": "7457297286"
    }, {
      "id": 13,
      "first_name": "Aluino",
      "last_name": "Norrey",
      "email": "anorreyc@pen.io",
      "gender": "Male",
      "mobile": "0175371113"
    }, {
      "id": 14,
      "first_name": "Damiano",
      "last_name": "Balderston",
      "email": "dbalderstond@list-manage.com",
      "gender": "Male",
      "mobile": "3952420492"
    }, {
      "id": 15,
      "first_name": "Lewiss",
      "last_name": "Butt Gow",
      "email": "lbuttgowe@studiopress.com",
      "gender": "Male",
      "mobile": "5784752588"
    }, {
      "id": 16,
      "first_name": "Jedidiah",
      "last_name": "Ojeda",
      "email": "jojedaf@wiley.com",
      "gender": "Male",
      "mobile": "9777662599"
    }, {
      "id": 17,
      "first_name": "Case",
      "last_name": "Novik",
      "email": "cnovikg@topsy.com",
      "gender": "Male",
      "mobile": "7365211342"
    }, {
      "id": 18,
      "first_name": "Gayleen",
      "last_name": "Wardhough",
      "email": "gwardhoughh@sfgate.com",
      "gender": "Female",
      "mobile": "7509295203"
    }, {
      "id": 19,
      "first_name": "Cyrill",
      "last_name": "Hartle",
      "email": "chartlei@blinklist.com",
      "gender": "Male",
      "mobile": "1060242184"
    }, {
      "id": 20,
      "first_name": "Gypsy",
      "last_name": "Youd",
      "email": "gyoudj@istockphoto.com",
      "gender": "Female",
      "mobile": "5601774412"
    }
  ]